-- MySQL Script generated by MySQL Workbench
-- Model: PatoralBancoDados    Version: 1.0 
-- Aluna: Ana Clara Lonczynski
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PatoralBancoDados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Beneficiado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Beneficiado` (
  `CPF` VARCHAR(11) NOT NULL,
  `Primeiro_nome` VARCHAR(60) NULL,
  `Sobrenome` VARCHAR(60) NULL,
  `Data_nascimento` DATETIME NULL,
  `Endereco` VARCHAR(80) NULL,
  `Sexo` CHAR(1) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Campanha` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(50) NULL,
  `Meta_arrecadacao` DECIMAL(2) NULL,
  `Status` CHAR(1) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categoia_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categoia_item` (
  `Id` INT NOT NULL,
  `Descricao` VARCHAR(140) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Doacao` (
  `Codigo` VARCHAR(10) NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  `Data` DATETIME NULL,
  `Doador_CPF` VARCHAR(11) NOT NULL,
  `Posto_de_coleta_Codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Doacao_Doador_idx` (`Doador_CPF` ASC) VISIBLE,
  INDEX `fk_Doacao_Posto_de_coleta1_idx` (`Posto_de_coleta_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Doacao_Doador`
    FOREIGN KEY (`Doador_CPF`)
    REFERENCES `Doador` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doacao_Posto_de_coleta1`
    FOREIGN KEY (`Posto_de_coleta_Codigo`)
    REFERENCES `Posto_de_coleta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Doador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Doador` (
  `CPF` VARCHAR(11) NOT NULL,
  `Primeiro_nome` VARCHAR(60) NULL,
  `Sobrenome` VARCHAR(60) NULL,
  `Telefone` VARCHAR(17) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Entrega_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Entrega_posto` (
  `Posto_de_coleta_Codigo` VARCHAR(10) NOT NULL,
  `Codigo` VARCHAR(10) NOT NULL,
  `Data` DATETIME NULL,
  `Descricao` VARCHAR(140) NULL,
  `Beneficiado_CPF` VARCHAR(11) NOT NULL,
  `Item_Doacao_Codigo` VARCHAR(10) NOT NULL,
  `Item_Id` INT NOT NULL,
  `Voluntario_Matricula` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Posto_de_coleta_Codigo`, `Codigo`),
  INDEX `fk_Entrega_posto_Beneficiado1_idx` (`Beneficiado_CPF` ASC) VISIBLE,
  INDEX `fk_Entrega_posto_Posto_de_coleta1_idx` (`Posto_de_coleta_Codigo` ASC) VISIBLE,
  INDEX `fk_Entrega_posto_Item1_idx` (`Item_Doacao_Codigo` ASC, `Item_Id` ASC) VISIBLE,
  INDEX `fk_Entrega_posto_Voluntario1_idx` (`Voluntario_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Entrega_posto_Beneficiado1`
    FOREIGN KEY (`Beneficiado_CPF`)
    REFERENCES `Beneficiado` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_posto_Posto_de_coleta1`
    FOREIGN KEY (`Posto_de_coleta_Codigo`)
    REFERENCES `Posto_de_coleta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_posto_Item1`
    FOREIGN KEY (`Item_Doacao_Codigo` , `Item_Id`)
    REFERENCES `Item` (`Doacao_Codigo` , `Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrega_posto_Voluntario1`
    FOREIGN KEY (`Voluntario_Matricula`)
    REFERENCES `Voluntario` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Item` (
  `Doacao_Codigo` VARCHAR(10) NOT NULL,
  `Id` INT NOT NULL,
  `Descricao` VARCHAR(140) NULL,
  `Quantidade` INT NULL,
  `Categoia_item_Id` INT NOT NULL,
  PRIMARY KEY (`Doacao_Codigo`, `Id`),
  INDEX `fk_Item_Doacao1_idx` (`Doacao_Codigo` ASC) VISIBLE,
  INDEX `fk_Item_Categoia_item1_idx` (`Categoia_item_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Doacao1`
    FOREIGN KEY (`Doacao_Codigo`)
    REFERENCES `Doacao` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_Categoia_item1`
    FOREIGN KEY (`Categoia_item_Id`)
    REFERENCES `Categoia_item` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parceiros_campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parceiros_campanha` (
  `Nome` VARCHAR(50) NOT NULL,
  `Campanha_Id` INT NOT NULL,
  PRIMARY KEY (`Nome`, `Campanha_Id`),
  INDEX `fk_Parceiros_campanha_Campanha1_idx` (`Campanha_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Parceiros_campanha_Campanha1`
    FOREIGN KEY (`Campanha_Id`)
    REFERENCES `Campanha` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Parceiros_posto_de_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Parceiros_posto_de_coleta` (
  `Nome` VARCHAR(50) NOT NULL,
  `Posto_de_coleta_Codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Nome`, `Posto_de_coleta_Codigo`),
  INDEX `fk_Parceiros_posto_de_coleta_Posto_de_coleta1_idx` (`Posto_de_coleta_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Parceiros_posto_de_coleta_Posto_de_coleta1`
    FOREIGN KEY (`Posto_de_coleta_Codigo`)
    REFERENCES `Posto_de_coleta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Posto_de_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Posto_de_coleta` (
  `Codigo` VARCHAR(10) NOT NULL,
  `Endereco` VARCHAR(80) NULL,
  `Nome` VARCHAR(40) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Realizar_Posto_Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Realizar_Posto_Campanha` (
  `Posto_de_coleta_Codigo` VARCHAR(10) NOT NULL,
  `Campanha_Id` INT NOT NULL,
  `Data_inicio` DATETIME NULL,
  `Data_fim` DATETIME NULL,
  PRIMARY KEY (`Posto_de_coleta_Codigo`, `Campanha_Id`),
  INDEX `fk_Posto_de_coleta_has_Campanha_Campanha1_idx` (`Campanha_Id` ASC) VISIBLE,
  INDEX `fk_Posto_de_coleta_has_Campanha_Posto_de_coleta1_idx` (`Posto_de_coleta_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Posto_de_coleta_has_Campanha_Posto_de_coleta1`
    FOREIGN KEY (`Posto_de_coleta_Codigo`)
    REFERENCES `Posto_de_coleta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posto_de_coleta_has_Campanha_Campanha1`
    FOREIGN KEY (`Campanha_Id`)
    REFERENCES `Campanha` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Voluntario` (
  `Matricula` VARCHAR(20) NOT NULL,
  `Primeiro_nome` VARCHAR(60) NULL,
  `Sobrenome` VARCHAR(60) NULL,
  `Telefone` VARCHAR(17) NULL,
  `Email` VARCHAR(45) NULL,
  `Posto_de_coleta_Codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `fk_Voluntario_Posto_de_coleta1_idx` (`Posto_de_coleta_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_Voluntario_Posto_de_coleta1`
    FOREIGN KEY (`Posto_de_coleta_Codigo`)
    REFERENCES `Posto_de_coleta` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
