-- MySQL Script generated by MySQL Workbench
-- Sat Mar 15 23:28:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AREA` (
  `Sigla` VARCHAR(45) NOT NULL,
  `CURSO_Sigla` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `SuperArea` VARCHAR(45) NOT NULL,
  INDEX `fk_AREA_CURSO_idx` (`CURSO_Sigla` ASC) VISIBLE,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `fk_AREA_CURSO`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `mydb`.`CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CURSO` (
  `Sigla` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` INT NOT NULL,
  `Custo` DECIMAL(10) NOT NULL,
  `Area` VARCHAR(45) NOT NULL,
  `AREA_Sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_CURSO_AREA1_idx` (`AREA_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_CURSO_AREA1`
    FOREIGN KEY (`AREA_Sigla`)
    REFERENCES `mydb`.`AREA` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MODULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MODULO` (
  `CURSO_Sigla` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(40) NOT NULL,
  `Sigla` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Sigla`),
  INDEX `fk_MODULO_CURSO1_idx` (`CURSO_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_MODULO_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `mydb`.`CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TOPICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TOPICO` (
  `MODULO_Sigla` VARCHAR(20) NOT NULL,
  `Modulo` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Horas` INT NOT NULL,
  PRIMARY KEY (`Modulo`),
  INDEX `fk_TOPICO_MODULO1_idx` (`MODULO_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_TOPICO_MODULO1`
    FOREIGN KEY (`MODULO_Sigla`)
    REFERENCES `mydb`.`MODULO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `Sexo` CHAR(1) NOT NULL,
  `DataNasc` YEAR(8) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATRICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MATRICULA` (
  `Data` DATE NOT NULL,
  `Pago` BIT(1) NOT NULL,
  `ALUNO_CPF` INT(11) NOT NULL,
  `CURSO_Sigla` VARCHAR(20) NOT NULL,
  INDEX `fk_MATRICULA_ALUNO1_idx` (`ALUNO_CPF` ASC) VISIBLE,
  INDEX `fk_MATRICULA_CURSO1_idx` (`CURSO_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_MATRICULA_ALUNO1`
    FOREIGN KEY (`ALUNO_CPF`)
    REFERENCES `mydb`.`ALUNO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATRICULA_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `mydb`.`CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESSOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROFESSOR` (
  `CPF` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CURSO_Sigla` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_PROFESSOR_CURSO1_idx` (`CURSO_Sigla` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESSOR_CURSO1`
    FOREIGN KEY (`CURSO_Sigla`)
    REFERENCES `mydb`.`CURSO` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
